name: frontend
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  flutter_svg: ^2.2.4
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  flutter_tts: ^4.2.5
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"        # ← for iOS + old Android
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"               # ← match your image bg color
  adaptive_icon_foreground: "assets/images/app_icon.jpg"
  remove_alpha_ios: true


flutter:
  assets:
    - .env
    - assets/images/
    - assets/animations/
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

