// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vwMID1A6gsPDo3NykkUxo7XDwWhqBf8',
    appId: '1:866824918074:web:fe04b18b74fe081c0ad103',
    messagingSenderId: '866824918074',
    projectId: 'story-telling-bot-b1a75',
    authDomain: 'story-telling-bot-b1a75.firebaseapp.com',
    storageBucket: 'story-telling-bot-b1a75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMC4ruoAA2erIJ-YDiJlIAyhnxDGOXbBA',
    appId: '1:866824918074:android:85d82b590f84ccb40ad103',
    messagingSenderId: '866824918074',
    projectId: 'story-telling-bot-b1a75',
    storageBucket: 'story-telling-bot-b1a75.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0vwMID1A6gsPDo3NykkUxo7XDwWhqBf8',
    appId: '1:866824918074:web:43358dd4c23adf140ad103',
    messagingSenderId: '866824918074',
    projectId: 'story-telling-bot-b1a75',
    authDomain: 'story-telling-bot-b1a75.firebaseapp.com',
    storageBucket: 'story-telling-bot-b1a75.firebasestorage.app',
  );
}
